version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: hourly
    allow:
      - dependency-type: all
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: hourly
    allow:
      - dependency-type: all
